/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package josuezelaya_lab7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Juego_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Juego_Ventana
     */
    public Juego_Ventana() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_principal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_nickname = new javax.swing.JTextField();
        sp_ataque = new javax.swing.JSpinner();
        sp_defensa = new javax.swing.JSpinner();
        sp_salud = new javax.swing.JSpinner();
        tab_tipo_guerreo = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        cb_tipo_bestia = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_numcuenta = new javax.swing.JTextField();
        tf_carrera = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        boton_guardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cb_listar = new javax.swing.JComboBox<>();
        mostrar_boton = new javax.swing.JButton();
        boton_modificar = new javax.swing.JButton();
        tf_fila = new javax.swing.JTextField();
        tf_columna = new javax.swing.JTextField();
        tf_nuevovalor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Guerreros");

        jLabel2.setText("Nombre");

        jLabel3.setText("Nickname");

        jLabel4.setText("Poder de Ataque");

        jLabel5.setText("Poder de Defensa");

        jLabel6.setText("Salud");

        sp_ataque.setValue(200);

        sp_defensa.setValue(25);

        sp_salud.setValue(800);

        cb_tipo_bestia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dragon", "Fenix", "Hombre Lobo", "Minotauro" }));

        jLabel7.setText("Ingrese tipo de Bestia");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(cb_tipo_bestia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tipo_bestia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        tab_tipo_guerreo.addTab("Bestia", jPanel4);

        jLabel8.setText("N° Cuenta");

        jLabel9.setText("Carrera");

        jLabel10.setText("Edad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_numcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(tf_carrera)
                    .addComponent(tf_edad))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tab_tipo_guerreo.addTab("Alumno", jPanel5);

        boton_guardar.setText("Guardar");
        boton_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sp_salud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sp_defensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sp_ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(90, 90, 90)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                            .addComponent(tf_nickname)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addComponent(tab_tipo_guerreo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tab_tipo_guerreo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sp_ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_defensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_salud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        tab_principal.addTab("Agregar", jPanel1);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        cb_listar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dragon", "Fenix", "Hombre Lobo", "Minotauro", "Alumno" }));

        mostrar_boton.setText("Mostrar");
        mostrar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrar_botonMouseClicked(evt);
            }
        });

        boton_modificar.setText("Modificar");
        boton_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_modificarMouseClicked(evt);
            }
        });

        jLabel11.setText("Fila");

        jLabel12.setText("Columna");

        jLabel13.setText("Nuevo Vallor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(mostrar_boton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(boton_modificar)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(tf_nuevovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar_boton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nuevovalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(boton_modificar)
                .addGap(174, 174, 174))
        );

        tab_principal.addTab("Listar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        tab_principal.addTab("Simulacion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardarMouseClicked
        // boton agregar guerreros

        String nombre = tf_nombre.getText();
        String nickname = tf_nickname.getText();
        double poder_ataque = Double.parseDouble(sp_ataque.getValue().toString());
        double poder_defensa = Double.parseDouble(sp_defensa.getValue().toString());
        double salud = Double.parseDouble(sp_salud.getValue().toString());
        if  (salud <800){
            JOptionPane.showMessageDialog(this, "Tiene que ser mayor a 800 la salud");
            sp_salud.setValue(800);
        }
       if  (poder_ataque<200 || poder_ataque>300){
            JOptionPane.showMessageDialog(this, "Tiene que ser mayor a 200  el poder de ataque o menor que 300");
            sp_ataque.setValue(200);
        }
       if  (poder_defensa<25 || poder_defensa>75){
            JOptionPane.showMessageDialog(this, "Tiene que ser mayor a 25  el poder de dfensa o menor que 75");
            sp_defensa.setValue(25);
        }
        if (tab_tipo_guerreo.getSelectedIndex() == 0) {
            if (cb_tipo_bestia.getSelectedItem().toString().equals("Dragon")) {
                guerrero.add(new Dragon(nombre, nickname, poder_ataque, poder_defensa, salud, 0));
                binarioag = new AdminGuerreros("./Guerrero_ Dragon.cbm");
                for (int i = 0; i < guerrero.size(); i++) {
                    binarioag.cargarArchivo();
                    binarioag.setGuerrero(((Guerreros) guerrero.get(i)));
                    binarioag.escribirArchivo();
                }
                JOptionPane.showMessageDialog(this, "Se agrego Dragon");
            } else if (cb_tipo_bestia.getSelectedItem().toString().equals("Fenix")) {
                guerrero.add(new Fenix(nombre, nickname, poder_ataque, poder_defensa, salud, 0));
                binarioag = new AdminGuerreros("./Guerrero_ Fenix.cbm");
                for (int i = 0; i < guerrero.size(); i++) {
                    binarioag.cargarArchivo();
                    binarioag.setGuerrero(((Guerreros) guerrero.get(i)));
                    binarioag.escribirArchivo();
                }
                JOptionPane.showMessageDialog(this, "Se agrego Fenix");
            } else if (cb_tipo_bestia.getSelectedItem().toString().equals("Hombre Lobo")) {
                guerrero.add(new Hombre_Lobo(nombre, nickname, poder_ataque, poder_defensa, salud, 0));
                binarioag = new AdminGuerreros("./Guerrero_Hombre_Lobo.cbm");
                for (int i = 0; i < guerrero.size(); i++) {
                    binarioag.cargarArchivo();
                    binarioag.setGuerrero(((Guerreros) guerrero.get(i)));
                    binarioag.escribirArchivo();
                }
                JOptionPane.showMessageDialog(this, "Se agrego Hombre Lobo");
            } else if (cb_tipo_bestia.getSelectedItem().toString().equals("Minotauro")) {

                guerrero.add(new Minotauro(nombre, nickname, poder_ataque, poder_defensa, salud, 0));
                binarioag = new AdminGuerreros("./Guerrero_Minotauro.cbm");
                for (int i = 0; i < guerrero.size(); i++) {
                    binarioag.cargarArchivo();
                    binarioag.setGuerrero(((Guerreros) guerrero.get(i)));
                    binarioag.escribirArchivo();
                }
                JOptionPane.showMessageDialog(this, "Se agrego Minotauro");
            }

        } else if (tab_tipo_guerreo.getSelectedIndex() == 1) {
            long num_cuenta = Long.parseLong(tf_numcuenta.getText());
            String carrera = tf_carrera.getText();
            int edad = Integer.parseInt(tf_edad.getText());
            guerrero.add(new Alumnos(num_cuenta, carrera, edad, nombre, nickname, poder_ataque, poder_defensa, salud, 0));
            binarioag = new AdminGuerreros("./Alumno.cbm");
                for (int i = 0; i < guerrero.size(); i++) {
                    binarioag.cargarArchivo();
                    binarioag.setGuerrero(((Alumnos) guerrero.get(i)));
                    binarioag.escribirArchivo();
                }
                JOptionPane.showMessageDialog(this, "Se agrego Alumno");
        }
    }//GEN-LAST:event_boton_guardarMouseClicked

    private void mostrar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrar_botonMouseClicked
        // TODO add your handling code here:
        if (cb_listar.getSelectedItem().toString().equals("Dragon")){
            DefaultTableModel modelo
                        = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("Nickname");
                modelo.addColumn("Poder de Ataque");
                modelo.addColumn("Poder de Defensa");
                modelo.addColumn("salud");
                modelo.addColumn("Puntos");
                for (int i = 0; i < guerrero.size(); i++) {
                Dragon d=(Dragon)guerrero.get(i);
                if (d instanceof Dragon){
                    Object [] newrow={
                        d.getNombre(), d.getNickname(), d.getPoder_ataque(), d.getPoder_defensa(), d.getSalud(), d.getPuntos()
                    };
                    modelo.addRow(newrow);
                }
            };
            tabla.setModel(modelo);
        }
        if (cb_listar.getSelectedItem().toString().equals("Fenix")){
             DefaultTableModel modelo
                        = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("Nickname");
                modelo.addColumn("Poder de Ataque");
                modelo.addColumn("Poder de Defensa");
                modelo.addColumn("salud");
                modelo.addColumn("Puntos");
                for (int i = 0; i < guerrero.size(); i++) {
                Fenix d=(Fenix)guerrero.get(i);
                if (d instanceof Fenix){
                    Object [] newrow={
                        d.getNombre(), d.getNickname(), d.getPoder_ataque(), d.getPoder_defensa(), d.getSalud(), d.getPuntos()
                    };
                    modelo.addRow(newrow);
                }
            };
            tabla.setModel(modelo);
        }
        if (cb_listar.getSelectedItem().toString().equals("Hombre Lobo")){
             DefaultTableModel modelo
                        = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("Nickname");
                modelo.addColumn("Poder de Ataque");
                modelo.addColumn("Poder de Defensa");
                modelo.addColumn("salud");
                modelo.addColumn("Puntos");
                for (int i = 0; i < guerrero.size(); i++) {
                Hombre_Lobo d=(Hombre_Lobo)guerrero.get(i);
                if (d instanceof Hombre_Lobo){
                    Object [] newrow={
                        d.getNombre(), d.getNickname(), d.getPoder_ataque(), d.getPoder_defensa(), d.getSalud(), d.getPuntos()
                    };
                    modelo.addRow(newrow);
                }
            };
            tabla.setModel(modelo);
        }
        if (cb_listar.getSelectedItem().toString().equals("Minotauro")){
             DefaultTableModel modelo
                        = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("Nickname");
                modelo.addColumn("Poder de Ataque");
                modelo.addColumn("Poder de Defensa");
                modelo.addColumn("salud");
                modelo.addColumn("Puntos");
                for (int i = 0; i < guerrero.size(); i++) {
               Minotauro d=(Minotauro)guerrero.get(i);
                if (d instanceof Minotauro){
                    Object [] newrow={
                        d.getNombre(), d.getNickname(), d.getPoder_ataque(), d.getPoder_defensa(), d.getSalud(), d.getPuntos()
                    };
                    modelo.addRow(newrow);
                }
            };
            tabla.setModel(modelo);
        }
        if (cb_listar.getSelectedItem().toString().equals("Alumno")){
             DefaultTableModel modelo
                        = new DefaultTableModel();
                modelo.addColumn("Nombre");
                modelo.addColumn("N° Cuenta");
                modelo.addColumn("Carrera");
                modelo.addColumn("Edad");
                
                for (int i = 0; i < guerrero.size(); i++) {
                Alumnos d=(Alumnos)guerrero.get(i);
                if (d instanceof Alumnos){
                    Object [] newrow={
                        d.getNombre(), d.getNum_cuenta(), d.getCarrera(), d.getEdad()
                    };
                    modelo.addRow(newrow);
                }
            };
            tabla.setModel(modelo);
        }
    }//GEN-LAST:event_mostrar_botonMouseClicked

    private void boton_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_modificarMouseClicked
        // TODO add your handling code here:
        int fila=Integer.parseInt(tf_fila.getText());
        int columna=Integer.parseInt(tf_columna.getText());
        tabla.setValueAt(tf_nuevovalor.getText(), fila, columna);
    }//GEN-LAST:event_boton_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JComboBox<String> cb_listar;
    private javax.swing.JComboBox<String> cb_tipo_bestia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrar_boton;
    private javax.swing.JSpinner sp_ataque;
    private javax.swing.JSpinner sp_defensa;
    private javax.swing.JSpinner sp_salud;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTabbedPane tab_tipo_guerreo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_columna;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_fila;
    private javax.swing.JTextField tf_nickname;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nuevovalor;
    private javax.swing.JTextField tf_numcuenta;
    // End of variables declaration//GEN-END:variables
ArrayList guerrero = new ArrayList();
    AdminGuerreros binarioag;
}
